### ISSUE TITLE
Tutorial for host own mcassoc

### ISSUE THREAD

**Issue by xion87** [lukegb/mcassoc#19]
I would like to know how to host the mcassoc on my linux macchine, thank you :)

**Comment by lukegb** [comment]
This is no longer possible. MCAssoc is now only intended to run on Google AppEngine - but can be done so fairly easily.

1. Install the `gcloud` utilities on your machine.
1. Create a new project in the Google Cloud Platform console. Since MCAssoc relies on using a Cloud Storage bucket, you'll also need to enable billing.
1. Create a new bucket under the "Storage" section of the console. Name it something sensible and remember it - you'll need the name in a sec.
1. Grant "allUsers" the Storage Object Reader role to your new bucket.
1. Consider setting up a lifecycle to automatically delete old skins from the bucket.
1. Clone the `mcassoc` repository.
1. Create a new "keys.go" file in the checkin with some content that looks similar to:
```go
package mcassoc

var (
	sesskey    = []byte("someRandomKeyHere")
	authkey    = "aDifferentRandomKey"
	dvKey      = []byte("anotherRandomKey")
	stathatkey = "" // leave this blank
)
```
1. Find the `client.Bucket("mcassoc-temp")` and swap it for `client.Bucket("your-bucket-name")`.
1. Run `gcloud app deploy` and wait. You'll probably have to pick a new AppEngine region.
1. Once the deploy has completed, go back to the Cloud Platform console, pick "IAM" from the left-hand sidebar, and grant the App Engine service account access to the Storage Object Writer role.
1. You should be done.
